#!/bin/sh
set -eu

: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${LEDGERBRIDGE_APP_DB_PASSWORD:?LEDGERBRIDGE_APP_DB_PASSWORD is required}"
: "${LEDGERBRIDGE_API_DB_PASSWORD:?LEDGERBRIDGE_API_DB_PASSWORD is required}"
: "${LEDGERBRIDGE_WORKER_DB_PASSWORD:?LEDGERBRIDGE_WORKER_DB_PASSWORD is required}"
: "${LEDGERBRIDGE_READER_DB_PASSWORD:?LEDGERBRIDGE_READER_DB_PASSWORD is required}"

if [ "$LEDGERBRIDGE_APP_DB_PASSWORD" = "$LEDGERBRIDGE_API_DB_PASSWORD" ] \
    || [ "$LEDGERBRIDGE_APP_DB_PASSWORD" = "$LEDGERBRIDGE_WORKER_DB_PASSWORD" ] \
    || [ "$LEDGERBRIDGE_API_DB_PASSWORD" = "$LEDGERBRIDGE_WORKER_DB_PASSWORD" ] \
    || [ "$LEDGERBRIDGE_READER_DB_PASSWORD" = "$LEDGERBRIDGE_APP_DB_PASSWORD" ] \
    || [ "$LEDGERBRIDGE_READER_DB_PASSWORD" = "$LEDGERBRIDGE_API_DB_PASSWORD" ] \
    || [ "$LEDGERBRIDGE_READER_DB_PASSWORD" = "$LEDGERBRIDGE_WORKER_DB_PASSWORD" ]; then
    echo "runtime database passwords must be distinct" >&2
    exit 1
fi

psql --no-psqlrc --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
    --set=ON_ERROR_STOP=1 \
    --set=app_password="$LEDGERBRIDGE_APP_DB_PASSWORD" \
    --set=api_password="$LEDGERBRIDGE_API_DB_PASSWORD" \
    --set=worker_password="$LEDGERBRIDGE_WORKER_DB_PASSWORD" \
    --set=reader_password="$LEDGERBRIDGE_READER_DB_PASSWORD" <<'SQL'
SELECT format(
    'CREATE ROLE ledgerbridge_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD %L',
    :'app_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledgerbridge_app') \gexec

ALTER ROLE ledgerbridge_app
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS
    PASSWORD :'app_password';

SELECT format(
    'CREATE ROLE ledgerbridge_api LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD %L',
    :'api_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledgerbridge_api') \gexec

ALTER ROLE ledgerbridge_api
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS
    PASSWORD :'api_password';

SELECT format(
    'CREATE ROLE ledgerbridge_worker LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD %L',
    :'worker_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledgerbridge_worker') \gexec

ALTER ROLE ledgerbridge_worker
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS
    PASSWORD :'worker_password';

SELECT format(
    'CREATE ROLE ledgerbridge_reader LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD %L',
    :'reader_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledgerbridge_reader') \gexec

ALTER ROLE ledgerbridge_reader
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS
    PASSWORD :'reader_password';

SELECT format(
    'REVOKE TEMPORARY ON DATABASE %I FROM PUBLIC',
    current_database()
) \gexec
SQL
