import type { Candidate } from './types'

export const initialCandidates: Candidate[] = [
  {
    id: 'C-8F21',
    source: 'Telegram',
    receivedAt: '今天 09:42',
    sender: '酒店财务',
    businessUnit: '城南店',
    category: '布草',
    amount: 6380,
    accountingMonth: '2026-08',
    summary: '城南店 8 月布草清洗费用，供应商月结单',
    evidence: '财务 城南店8月布草清洗费6380元，账单见附件。',
    attachment: '城南店_8月布草账单.pdf',
    confidence: 0.96,
    status: 'pending',
  },
  {
    id: 'C-7A64',
    source: '钉钉',
    receivedAt: '今天 08:16',
    sender: '采购负责人',
    businessUnit: '江景店',
    category: '瓶装水',
    amount: 2148,
    accountingMonth: '2026-08',
    summary: '江景店瓶装水采购，数量与单价已从附件提取',
    evidence: '江景店这批水已到，财务记在八月份，合计2148。',
    attachment: '送货单_0822.jpg',
    confidence: 0.91,
    status: 'pending',
  },
  {
    id: 'C-62D9',
    source: '微信',
    receivedAt: '昨天 17:35',
    sender: '店长',
    businessUnit: '机场店',
    category: '水费',
    amount: 4832.6,
    accountingMonth: null,
    summary: '机场店水费，原消息未说明归属月份',
    evidence: '机场店这次水费4832.60，缴费回单发你了。',
    attachment: '水费回单.png',
    confidence: 0.88,
    status: 'pending',
    incomplete: true,
  },
  {
    id: 'C-5B17',
    source: 'Telegram',
    receivedAt: '昨天 14:02',
    sender: '酒店财务',
    businessUnit: '城南店',
    category: '银行收款',
    amount: 12680,
    accountingMonth: '2026-08',
    summary: '城南店银行收款，与另一条候选金额和凭证号冲突',
    evidence: '城南店收款12680元，流水尾号9321。',
    confidence: 0.94,
    status: 'pending',
    conflict: true,
  },
  {
    id: 'C-49E3',
    source: '钉钉',
    receivedAt: '8月21日 11:28',
    sender: '酒店财务',
    businessUnit: '江景店',
    category: '税费',
    amount: 9240.5,
    accountingMonth: '2026-08',
    summary: '江景店本月税费缴款',
    evidence: '江景店本月税费9240.50，电子缴款书已上传。',
    attachment: '电子缴款书.pdf',
    confidence: 0.98,
    status: 'confirmed',
  },
]

export const reconciliationRows = [
  { unit: '城南店', water: 5120.8, tax: 11340, linen: 6380, bottledWater: 1876, receipts: 42860, readiness: '有冲突' },
  { unit: '江景店', water: 6094.2, tax: 9240.5, linen: 7420, bottledWater: 2148, receipts: 51620, readiness: '可生成' },
  { unit: '机场店', water: 0, tax: 10680, linen: 5890, bottledWater: 2360, receipts: 39240, readiness: '缺月份' },
]
